### ISSUE TITLE
Possibly switched flags for self.geometry in RobustLoss

### ISSUE THREAD

**Issue by harvineet** [daniellevy/fast-dro#1]
Thank you for releasing the code! It is quite readable.

I think the logic for cvar and chi-square is flipped in the `RobustLoss.best_response` https://github.com/daniellevy/fast-dro/blob/main/robust_losses.py#L147

**Comment by daniellevy** [comment]
Hi Harvineet,

I don't think we are: in the case of CVaR, with regularization we bisect over the log-sum-exp and without we simply return the largest \alpha losses. In the case of chi-square, we bisect over the appropriate dual.

What makes you think that this is reversed?

Thanks for your interest and for looking carefully through our code in any case!

Best,
Daniel

**Comment by harvineet** [comment]
My bad. I looked at the torch.relu in chi-square and jumped to the conclusion that it is solving the CVaR dual. Did not read the `bisection_target` carefully.
